services:
  sysbench:
    build: .
    volumes:
      - .:/sysbench
    environment:
      - INSTANCE_COUNT=${INSTANCE_COUNT}
      - SYSBENCH_WORK_DIR=/sysbench/results
    working_dir: /sysbench
    entrypoint: ["/sysbench/sysbench_single.sh"]
